# Generated by Django 2.1.5 on 2019-02-16 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20190215_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slogan', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='organization')),
                ('image', models.ImageField(blank=True, null=True, upload_to='organization')),
                ('address', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=20)),
                ('mission', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('mobile1', models.CharField(max_length=20, null=True)),
                ('mobile2', models.CharField(max_length=20, null=True)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('about', models.TextField()),
                ('established', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
